# Generated by Django 3.0.8 on 2020-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemdesc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('helper_id', models.IntegerField()),
                ('reacher_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('reacher_score', models.IntegerField()),
                ('helper_score', models.IntegerField()),
                ('bargain_price', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
